- import_tasks: applications-install.yml
- import_tasks: applications-settings.yml

- import_tasks: dotfiles.yml
# - import_tasks: profiles.yml
- import_tasks: pgp.yml
# - import_tasks: pki.yml

- import_tasks: fonts.yml

- import_tasks: osx.yml
